exports.getUsers = {
  rows: [
    {
      user_id: 1,
      username: 'DudeAbides',
      email: 'test@abc.com',
      password_hash: 'test',
      first_name: 'Dude',
      last_name: 'Abides',
      date_of_birth: '01/01/1900',
      phone_number: '9876543210',
      address: '123 Main St',
      city: 'Normal',
      state: 'IL',
      zip: 60010,
      verified: true,
      last_login: null,
      created_by: 1,
      created_date: '2023-07-31 15:40:00.198068',
      updated_by: null,
      updated_date: null,
    },
    {
      user_id: 2,
      username: 'StupidAbides',
      email: 'test2@abc.com',
      password_hash: 'test',
      first_name: 'Stupid',
      last_name: 'Abides',
      date_of_birth: '01/01/1900',
      phone_number: '9876543210',
      address: '123 Main St',
      city: 'Normal',
      state: 'IL',
      zip: 60010,
      verified: false,
      last_login: null,
      created_by: 1,
      created_date: '2023-07-31 15:40:00.198068',
      updated_by: null,
      updated_date: null,
    },
  ],
};
