exports.userTableFields = {
  id: 'user_id',
  username: 'username',
  email: 'email',
  firstName: 'first_name',
  lastName: 'last_name',
  dob: 'date_of_birth',
  phone: 'phone_number',
  address: 'address',
  city: 'city',
  state: 'state',
  zip: 'zip',
  country: 'country',
  lastLogin: 'last_login',
  verified: 'verfied',
  createdDate: 'created_date',
  createdBy: 'created_by',
  updatedDate: 'updated_date',
  updatedBy: 'updated_by',
};

exports.usersRolesTableFields = {
  id: 'user_role_id',
  userId: 'user_id',
  roleId: 'role_id',
  createdDate: 'created_date',
  createdBy: 'created_by',
  updatedDate: 'updated_date',
  updatedBy: 'updated_by',
};
